services:
  - type: web
    name: nyaya-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python render_main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0